/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : ApplicationId,
  'status' : string,
  'appliedAt' : bigint,
  'workerId' : WorkerId,
  'jobId' : JobId,
  'workerName' : string,
}
export type ApplicationId = bigint;
export interface Job {
  'id' : JobId,
  'payPerDay' : bigint,
  'title' : string,
  'duration' : string,
  'active' : boolean,
  'postedBy' : string,
  'createdAt' : bigint,
  'description' : string,
  'skillsNeeded' : Array<string>,
  'location' : string,
}
export type JobId = bigint;
export interface UserProfile {
  'userType' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Worker {
  'id' : WorkerId,
  'bio' : string,
  'dailyRate' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'photoUrl' : string,
  'available' : boolean,
  'experience' : bigint,
  'rating' : number,
  'phone' : string,
  'reviewCount' : bigint,
  'skills' : Array<string>,
  'location' : string,
}
export type WorkerId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyToJob' : ActorMethod<[Application], ApplicationId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJob' : ActorMethod<[Job], JobId>,
  'createWorker' : ActorMethod<[Worker], WorkerId>,
  'deleteJob' : ActorMethod<[JobId], undefined>,
  'deleteWorker' : ActorMethod<[WorkerId], undefined>,
  'getAllJobs' : ActorMethod<[], Array<Job>>,
  'getAllWorkers' : ActorMethod<[], Array<Worker>>,
  'getApplicationsByJob' : ActorMethod<[JobId], Array<Application>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJob' : ActorMethod<[JobId], Job>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorker' : ActorMethod<[WorkerId], Worker>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchJobsBySkillAndLocation' : ActorMethod<[string, string], Array<Job>>,
  'searchWorkersBySkillAndLocation' : ActorMethod<
    [string, string],
    Array<Worker>
  >,
  'seedData' : ActorMethod<[], undefined>,
  'updateApplicationStatus' : ActorMethod<[ApplicationId, string], undefined>,
  'updateJob' : ActorMethod<[JobId, Job], undefined>,
  'updateWorker' : ActorMethod<[WorkerId, Worker], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];