/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ApplicationId = IDL.Nat;
export const WorkerId = IDL.Nat;
export const JobId = IDL.Nat;
export const Application = IDL.Record({
  'id' : ApplicationId,
  'status' : IDL.Text,
  'appliedAt' : IDL.Int,
  'workerId' : WorkerId,
  'jobId' : JobId,
  'workerName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Job = IDL.Record({
  'id' : JobId,
  'payPerDay' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'active' : IDL.Bool,
  'postedBy' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'skillsNeeded' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const Worker = IDL.Record({
  'id' : WorkerId,
  'bio' : IDL.Text,
  'dailyRate' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'photoUrl' : IDL.Text,
  'available' : IDL.Bool,
  'experience' : IDL.Nat,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'reviewCount' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToJob' : IDL.Func([Application], [ApplicationId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createJob' : IDL.Func([Job], [JobId], []),
  'createWorker' : IDL.Func([Worker], [WorkerId], []),
  'deleteJob' : IDL.Func([JobId], [], []),
  'deleteWorker' : IDL.Func([WorkerId], [], []),
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'getApplicationsByJob' : IDL.Func([JobId], [IDL.Vec(Application)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJob' : IDL.Func([JobId], [Job], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorker' : IDL.Func([WorkerId], [Worker], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchJobsBySkillAndLocation' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Job)],
      ['query'],
    ),
  'searchWorkersBySkillAndLocation' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Worker)],
      ['query'],
    ),
  'seedData' : IDL.Func([], [], []),
  'updateApplicationStatus' : IDL.Func([ApplicationId, IDL.Text], [], []),
  'updateJob' : IDL.Func([JobId, Job], [], []),
  'updateWorker' : IDL.Func([WorkerId, Worker], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ApplicationId = IDL.Nat;
  const WorkerId = IDL.Nat;
  const JobId = IDL.Nat;
  const Application = IDL.Record({
    'id' : ApplicationId,
    'status' : IDL.Text,
    'appliedAt' : IDL.Int,
    'workerId' : WorkerId,
    'jobId' : JobId,
    'workerName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Job = IDL.Record({
    'id' : JobId,
    'payPerDay' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'active' : IDL.Bool,
    'postedBy' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'skillsNeeded' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const Worker = IDL.Record({
    'id' : WorkerId,
    'bio' : IDL.Text,
    'dailyRate' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'photoUrl' : IDL.Text,
    'available' : IDL.Bool,
    'experience' : IDL.Nat,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'reviewCount' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToJob' : IDL.Func([Application], [ApplicationId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createJob' : IDL.Func([Job], [JobId], []),
    'createWorker' : IDL.Func([Worker], [WorkerId], []),
    'deleteJob' : IDL.Func([JobId], [], []),
    'deleteWorker' : IDL.Func([WorkerId], [], []),
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'getApplicationsByJob' : IDL.Func(
        [JobId],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJob' : IDL.Func([JobId], [Job], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorker' : IDL.Func([WorkerId], [Worker], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchJobsBySkillAndLocation' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Job)],
        ['query'],
      ),
    'searchWorkersBySkillAndLocation' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Worker)],
        ['query'],
      ),
    'seedData' : IDL.Func([], [], []),
    'updateApplicationStatus' : IDL.Func([ApplicationId, IDL.Text], [], []),
    'updateJob' : IDL.Func([JobId, Job], [], []),
    'updateWorker' : IDL.Func([WorkerId, Worker], [], []),
  });
};

export const init = ({ IDL }) => { return []; };